#1
SELECT COUNT(DISTINCT LAST_NAME) AS UNIQUE_NAME FROM ACTOR;
#2
SELECT COUNT(DISTINCT LANGUAGE_ID) AS LANGUAGE FROM FILM;
#3
SELECT COUNT(RATING) AS PG_13 FROM FILM WHERE RATING = "PG-13";
#4
SELECT TITLE, RELEASE_YEAR, LENGTH FROM FILM WHERE RELEASE_YEAR = "2006" ORDER BY LENGTH DESC LIMIT 10;
#5
SELECT * FROM RENTAL ORDER BY RENTAL_DATE ASC;
SELECT * , DATE_FORMAT(SUBSTRING(RENTAL_DATE, 1, 10),"%M %D, %Y") AS REAL_DATE FROM RENTAL ORDER BY RENTAL_DATE ASC LIMIT 1; 
# FIRST_DATE = 24/05/2005
SELECT *, DATE_FORMAT(SUBSTRING(RENTAL_DATE, 1, 10),"%M %D, %Y") AS REAL_DATE FROM RENTAL ORDER BY RENTAL_DATE DESC LIMIT 1; 
# LAST DATE = 14/02/2006
SELECT DATE_FORMAT(SUBSTRING(RENTAL_DATE, 1, 10),"%d/%m/%y") AS REAL_DATE, DATEDIFF("24/05/05", "14/02/06") AS OPERATING_TIME FROM RENTAL LIMIT 1;
# 6 AND 7
SELECT *, DATE_FORMAT(SUBSTRING(RENTAL_DATE, 1, 10),"%M") AS MONTH, 
DATE_FORMAT(SUBSTRING(RENTAL_DATE, 1, 10),"%W") AS WEEKDAY,
    CASE
	WHEN (DAYNAME(RENTAL_DATE) = "Saturday" OR "Sunday") THEN "Weekend"
	ELSE "Workday"
    END AS DAY_DATE
FROM RENTAL LIMIT 20;
# 8
SELECT DATE_FORMAT(SUBSTRING(RENTAL_DATE, 1, 10),"%d/%m/%y") AS REAL_DATE, COUNT(DATEDIFF("14/02/06", DATE_FORMAT(SUBSTRING(RENTAL_DATE, 1, 10),"%d/%m/%y"))) AS LAST_MONTHS_RENTAL  FROM  RENTAL
WHERE DATEDIFF("14/02/06", DATE_FORMAT(SUBSTRING(RENTAL_DATE, 1, 10),"%d/%m/%y")) < 31;